name: hello world
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 

      - name: List and Read file
        run: |
          echo "Hello World"
          ls -la
          cat README.md

      - name:     install cowsay
        run: sudo apt-get install cowsay -y

      - name: generate ascii artwork
        run: cowsay -f dragon "run for cover , i am a dragon" >> dragon.txt
      
      - name: read cowsay file
        run: cat dragon.txt
        
      